### PR TITLE
Add remember me feature

### PR DESCRIPTION
**Pull request by theboxer**
Add configurable remember me feature. By default it's set to 30days, where user can check a checkbox during a login. The login won't require Auth code for next 30 days.

### CODE REVIEW

**Comment by minagerges** [comment]
What is the benefit of that! 2FA  already spins around forcing users to use a token in addition to credentials, why would someone kill 2FA for a month or even a single login!

IMHO, implementing such feature renders 2FA useless as it totally kills the purpose of 2FA, if a user can disable it even for a single login.

**Comment by rthrash** [comment]
Google allows you to do it with Gmail and 2FA. If it's on a trusted computer, it sure saves a lot of back and forth copying and potentially mistyping codes. You wouldn't enable it on a public computer, though.

**Comment by minagerges** [comment]
Google implementation of "trusted computers" is different than this pull request. Trusted node should be based on additional implementation of different token algorithm rather than the one used for 2FA within the app. The trust is passed via additional cookie (to work independently from authentication one). Thus, such implementation requires a lot more than time based bypass. 
Accordingly, the Mechanism for computer trust should be
1- Based on a separate cookie than authentication one.
2- Must be separated from 2FA algorithms (secure coding considerations)

Not much of information in the link below. 
https://support.google.com/accounts/answer/2544838?hl=en

I'm not against the idea of course, but should be implemented in adequate way.

Been planning next release for a while, at least to cover ModX upgrade issue, following will implement a separate logic to bypass trusted computers. hopes for end of January.

Appreciate any input from experts like you @theboxer  @rthrash

**Comment by rthrash** [comment]
John and I were just speaking about that and may update the PR soon. :)

**Comment by minagerges** [comment]
Great. just remember to separate algorithms. An additional class is welcomed.

**Pull request closed without merging**
